### ISSUE TITLE
Hexlands don't work. Hexagons not spawning

### ISSUE THREAD

**Issue by IshimaKudzi** [alcatrazEscapee/hexlands#10]
Mod List:
AdFinders-1.19.3-8.1.2.0-build.0057.jar
AdLods-1.19.3-7.1.0.0-build.0001.jar
advancednetherite-1.14.6-1.19.3.jar
AdvancedSticks-1.19.3-(v.2.2.4).jar
almostunified-forge-1.19.3-0.3.6.jar
ancient_manuscripts-1.1.1-1.19.3.jar
appleskin-forge-mc1.19-2.4.2.jar
architectury-7.1.70-forge.jar
armorplus-1.19.3-19.2.0.jar
armorpointspp-forge-1.19.3-3.0.9.jar
artifacts-1.19.3-6.0.1.jar
assortedcore-1.19.3-6.0.1.jar
assortedstorage-1.19.3-7.1.0.jar
assortedtech-1.19.3-5.0.1.jar
assortedtools-1.19.3-7.0.1.jar
AttributeFix-Forge-1.19.3-18.0.1.jar
automaticdoors-1.19.3-4.4.jar
azurelib-forge-1.19.3-1.0.8.jar
balm-forge-1.19.3-5.0.3.jar
baubley-heart-canisters-1.19.3-1.1.0.jar
bdlib-1.26.0.4-mc1.19.3.jar
bettercombat-forge-1.6.2+1.19.3.jar
bettercreeper-1.19.3_1.2.2.jar
betterfpsdist-1.19.3-2.8.jar
betterleveling-1.19.3-0.5.0.jar
bettersafebed-forge-1.19-4.jar
betterspawnercontrol-1.19.3-4.0.jar
BetterTags-1.19.3-1.0.jar
bigbrain-1.19.3-1.6.3.jar
BiomeParticleWeather-v4.0.4-1.19.3-Forge.jar
BiomesOPlenty-1.19.3-17.2.0.537.jar
Bookshelf-Forge-1.19.3-17.0.5.jar
BorderlessWindow-1.19.1-1.5.2.jar
brutalbosses-1.19.3-6.1.jar
catalogue-1.7.0-1.19.3.jar
CharmOfReturn-forge-1.19.3-1.0.1-all.jar
citadel-2.3.0-1.19.3.jar
clienttweaks-forge-1.19.3-9.0.0.jar
cloth-config-9.0.94-forge.jar
Clumps-forge-1.19.3-9.0.0+16.jar
collective-1.19.3-6.53.jar
configured-2.0.2-1.19.3.jar
Controlling-forge-1.19.3-10.0+10.jar
corpse-1.19.3-1.0.2.jar
craftingcraft-forge-1.19.3-14.0.0.jar
ctov-3.1.8.jar
ctov-immersive-engineering-add-on-1.1.jar
ctov-waystone-compat-1.0.jar
curios-forge-1.19.3-5.1.4.0.jar
cursedearth-1.19.3-5.1.jar
custom-crosshair-mod-v1.5.3-forge-mc1.19.3.jar
customportalapi-0.0.3-forge-1.19.3.jar
CyclopsCore-1.19.3-1.18.2.jar
DiaboloLib-5.6.30.jar
Disenchanting-forge-1.19.3-2.2.2.jar
DisenchantmentEditTable-1.19.3-1.1.0.jar
DivineRPG-1.9.7.jar
dragon_enchants-1.0.5.jar
dungeonnowloading-17.0-1.19.3.jar
DungeonsArise-1.19.3-2.1.54-beta.jar
easyexperience-1.5.1.jar
easy_mob_farm_1.19.3-5.1.0.jar
EnchantmentDescriptions-Forge-1.19.3-14.0.7.jar
EnchantmentMachine-1.19.3-1.1.2.jar
ender-tendril-1.19.3-1.6.0.jar
endrem_forge-5.2.2-R-1.19.3.jar
energizedpower-1.19.3-1.4.2.jar
EnhancedAI-1.9.0-mc1.19.3.jar
EquipmentCompare-1.19.3-forge-1.3.2.jar
EverlastingAbilities-1.19.3-1.8.2.jar
expandedstorage-9.0.0-alpha.2+1.19.3-forge.jar
ExplorersCompass-1.19.3-1.3.0-forge.jar
FancyClear-Forge-1.19.3-1.4.1.jar
Fastload-Reforged-2.6.9+1.19.3.jar
ferritecore-5.1.0-forge.jar
forbidden_arcanus-1.19.3-2.2.0-beta2.jar
ForgeEndertech-1.19.3-10.1.0.1-build.0057.jar
gamemenumodoption-mc1.19.3-2.0.0.jar
geckolib-forge-1.19.3-4.0.4.jar
goprone-1.19.3-2.2.0.jar
HarderFarther-1.19.3-44.41.29.0.jar
harvestwithease-1.19.3-6.0.0.0-forge.jar
Healing+Bed+1.19.3.jar
hexlands-forge-1.19.3-4.1.0.jar
highlight-1.1.1-forge.jar
Highlighter-1.19.3-forge-1.1.4.jar
hourglass-1.19.1-1.2.1.1.jar
humblingbundle-1.19.3-2.1.jar
Iceberg-1.19.3-forge-1.1.2.jar
ImmersiveEngineering-1.19.3-9.3.0-163.jar
immersive_armors-1.5.4+1.19.3-forge.jar
incontrol-1.19.3-8.0.1.jar
InsaneLib-1.8.0-mc1.19.3.jar
InventoryProfilesNext-forge-1.19.3-1.9.3.jar
ironfurnaces-1.19.3-3.7.3.jar
Jade-1.19.3-forge-9.4.1.jar
Janoeo+Foundation-8.12.0.90.jar
journeymap-1.19.3-5.9.4-forge.jar
JustEnoughAdvancements-1.19.3-4.1.0.jar
JustEnoughResources-1.19.3-1.3.2.198.jar
K-Turrets-2.2.24-1.19.3.jar
Kiwi-1.19.3-forge-9.1.1.jar
kotlinforforge-4.0.0-all.jar
LegendaryTooltips-1.19.3-forge-1.4.0.jar
letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar
lexchange-1.19.3-1.0.4.jar
Lexicon-1.19.2-(v.1.4.2).jar
libIPN-forge-1.19.3-2.0.3.jar
LibX-1.19.3-4.3.1.jar
lumberjack-2.3.4.jar
L_Enders_Cataclysm-0.73-1.19.3.jar
maenchants-1.19.3-6.1.0.jar
majrusz-library-1.19.3-3.3.0.jar
majruszs-accessories-1.19.3-1.1.4.jar
majruszs-difficulty-1.19.3-1.7.3.jar
majruszs-enchantments-1.19.3-1.8.1.jar
ManyIdeasCore-1.19.3-1.4.0.jar
ManyIdeasDoors-1.19.3-1.2.2.jar
maptooltip-forge-1.19.2-2.0.1.jar
material_elements_1.19.3-7.0.1.jar
MCDoom-Forge-1.19.3-4.3.10.jar
mcsa-forge-4.0.0+1.19.3.jar
mcw-bridges-2.0.6-mc1.19.3forge.jar
mcw-doors-1.0.8forge-mc1.19.3.jar
mcw-fences-1.0.7-mc1.19.3forge.jar
mcw-furniture-3.1.0-mc1.19.3forge.jar
mcw-lights-1.0.5-mc1.19.3forge.jar
mcw-roofs-2.2.3-mc1.19.3forge.jar
mcw-trapdoors-1.0.9-mc1.19.3forge.jar
mcw-windows-2.1.1-mc1.19.3forge.jar
merenc-forge-1.19.x-v1.11.jar
metalbarrels-1.19.3-5.1.jar
mining_helmet-1.19.3-2.1.1.jar
modelfix-1.12.jar
modonomicon-1.19.3-1.27.0.jar
MouseTweaks-forge-mc1.19.3-2.24.jar
mvs-3.1.7-1.19.3.jar
nohostilesaroundcampfire-1.19.3-5.4.jar
occultism-1.19.3-1.73.0.jar
output_file_name
overloadedarmorbar-1.19.3-7.1.jar
PassableFoliage-1.19.3-forge-6.0.0.jar
Patchouli-1.19.3-78.jar
player-animation-lib-forge-1.0.2+1.19.3.jar
pluto-mc1.19.3-0.0.8.jar
potionring-1.19.3-1.1.jar
Prism-1.19.3-forge-1.0.3.jar
puffish_skills-0.1.1-1.19.3-forge.jar
PuzzlesLib-v5.0.6-1.19.3-Forge.jar
radiantgear-forge-2.1.0+1.19.3.jar
radon-0.8.2.jar
RaysDongles-6.16+-+1.19.3.jar
RecipesLibrary-1.19.3-2.0.1.jar
RedstoneMagic-1.19.3-1.44.37.0.jar
redstonepen-1.19.3-forge-1.3.20.jar
Regrowth-1.19.3-44.41.31.1.jar
REIPluginCompatibilities-forge-10.0.49.jar
repurposed_structures-6.3.19+1.19.3-forge.jar
RoughlyEnoughItems-10.0.592.jar
RoughlyEnoughProfessions-forge-1.19.3-1.2.1.jar
rubidium-0.6.3.jar
Satako-6.1.6-1.19.3.jar
saturn-mc1.19.3-0.0.2.jar
ScalableCatsForce-2.13.10-build-15-with-library.jar
scalar_utils-1.19.3-5.1.1.jar
simplegrinder-1.0.jar
simplylight-1.19.3-1.4.5-build.46.jar
skillcloaks-1.19.3-1.1.0.jar
sleep+time+1.19.3.jar
SlimeReagent-1.0.0.jar
SmartBrainLib-forge-1.19.3-1.8.1.jar
soundphysics-forge-1.19.3-1.1.0.jar
spells_and_shields-1.19.3-1.10.0-LEGACY.jar
storageracks-1.19.3-1.1.5.jar
Structory-1.19-v1.3.jar
SurvivalPlus-1.19.3-0.1.7.jar
SurvivalPlus-Lightsabers-1.19.3-0.1.7.jar
technobauble-0.8.0.1-mc1.19.3.jar
TerraBlender-forge-1.19.3-2.1.0.153.jar
Terralith_v2.3.6.jar
TES-forge-1.19.3-1.0.2.jar
thedragonlib-1.19-1.0.0.jar
theurgy-1.19.3-1.3.0.jar
the_bumblezone-6.6.15+1.19.3-forge.jar
tinyredstone-1.19.3-4.2.5.jar
toolleveling-forge-1.19.3-1.4.4.jar
towns_and_towers_forge-1.10.1+1.19.3.jar
trade-cycling-forge-1.19.3-1.0.5.jar
Trajectory+Preview-5.0.0-1.19.3.jar
TravelersTitles-1.19.3-Forge-3.2.0.jar
ultris-5.6.7g.jar
unidentifiedenchantments-1.0.14.jar
unstructured-0.5.7-FORGE.jar
useful_backpacks-1.19.3-1.14.3.109.jar
u_team_core-1.19.3-4.5.3.240.jar
valhelsia_core-forge-1.19.3-0.5.1.jar
Wabi-Sabi-Structures-1.1.2-Forge.jar
waystones-forge-1.19.3-12.2.0.jar
xercamod-1.19.3-1.0.1.jar
xercamusic-1.19.3-1.1.0.jar
YungsApi-1.19.3-Forge-3.9.0.jar
YungsBetterDesertTemples-1.19.3-Forge-2.3.0.jar
YungsBetterDungeons-1.19.3-Forge-3.3.0.jar
YungsBetterMineshafts-1.19.3-Forge-3.3.0.jar
YungsBetterNetherFortresses-1.19.3-Forge-1.1.1.jar
YungsBetterStrongholds-1.19.3-Forge-3.3.0.jar
YungsExtras-1.19.3-Forge-3.2.0.jar
zmedievalmusic-1.19.2-2.0.jar
[1.19.3-forge]-Epic-Knights-7.11.jar

Datapacks not installed, World preset "HexLands", The game does not crash on world creation/launch.

**Comment by alcatrazEscapee** [comment]
> Terralith_v2.3.6.jar
>
> Datapacks not installed

Terralith **is** a datapack, which will override any choice of world preset, Hexlands included.
