### ISSUE TITLE
Crash on Forge 1.19.4 create world

### ISSUE THREAD

**Issue by MrKashew** [alcatrazEscapee/hexlands#12]
I understand the mod version is 1.19.3 - is this the reason - as most mods are cross compatible across 1.19.3 and 4
Also had lostcities cities enabled
[crash-2023-05-09_12.31.37-client.txt](https://github.com/alcatrazEscapee/hexlands/files/11435436/crash-2023-05-09_12.31.37-client.txt)

**Comment by alcatrazEscapee** [comment]
> as most mods are cross compatible across 1.19.3 and 4

No, they aren't. 1.19 sub versions have had huge internal changes that mean most mods are incompatible across minor versions, and Mojang has indicated this trend is going to continue.
