### ISSUE TITLE
Very unclear on how to customize

### ISSUE THREAD

**Issue by Entropy159** [alcatrazEscapee/hexlands#15]
The description for how to customize the hexes is very unclear. The example is even less than the file in the source code, showing none of the options for customization along with not telling where to place the files. Could you please elaborate on this?

**Comment by alcatrazEscapee** [comment]
The [examples](https://github.com/alcatrazEscapee/hexlands/blob/1.21.x/Common/src/main/resources/data/hexlands/worldgen/world_preset/hexlands.json) are exactly what is present in the mod itself. If you don't know how world generation datapacks work I suggest looking on the [Minecraft wiki](https://minecraft.wiki/w/World_preset_definition) for the basics i.e. where to place files.
