### ISSUE TITLE
Don't know if it's a bug

### ISSUE THREAD

**Issue by KuroPeach** [alcatrazEscapee/hexlands#16]
The packet specifies the range, but goes straight to bedrock
![image](https://github.com/alcatrazEscapee/hexlands/assets/19620848/42df5e1a-7dc4-41f1-9ec0-123196a87391)

**Comment by alcatrazEscapee** [comment]
The bottom border extends from the bottom of the world, to a height between `[min_height, max_height]` randomly chosen for each hex. This is correct behavior.
