### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by mojolowjo** [alcatrazEscapee/hexlands#18]
Why not add a config where players can change simple values like the biome scale and hex size?

**Comment by alcatrazEscapee** [comment]
[It already exists](https://github.com/alcatrazEscapee/hexlands?tab=readme-ov-file#configuration-data-packs---121)

**Comment by mojolowjo** [comment]
Let me clarify as I did not explain myself very well. I meant specifically being able to edit those values through the mods like "mod menu" which allows you to edit configs of mods if there is an available config.

**Comment by NixityNull** [comment]
I also feel this mod would benefit from the accessibility of in-game config menu mods
