### ISSUE TITLE
Hexlands II conflict with twilightforest

### ISSUE THREAD

**Issue by Royal-Jelly** [alcatrazEscapee/hexlands#2]
I'm pretty sure its not on you, but none of the boss structures from twilightforest spawn with the generator set to hexlands.

Just to be certain I'm not missing anything could you double check my config?
This is the gist of [my config](https://gist.github.com/Royal-Jelly/7ee8d1e97868325c533b2b20766f88e3)

**Comment by alcatrazEscapee** [comment]
Yes, that looks fine. From a cursory look at TF's code it would *appear* that they use a custom chunk generator, which controls their structure spawning - which is something HexLands would be rather unable to handle, seeing as it *also* replaces the chunk generator.

**Comment by Royal-Jelly** [comment]
That's a RIP, got shot down in minutes by the twilightforest team.

**Comment by alcatrazEscapee** [comment]
Well, I'm not really surprised. They can't support it for the same reason I can't support their chunk generator natively... there's only one chunk generator per world... you just have to pick.

**Comment by Royal-Jelly** [comment]
Compatibility ... I think may be possible with a custom chunk generator specifically implementing their [TFFeatures](https://github.com/TeamTwilight/twilightforest/blob/1.16.x/src/main/java/twilightforest/TFFeature.java). 
I wont ask you to go that far though, because that would set precedent that you may support other mods with the same flaw.

**Comment by Drullkus** [comment]
The good news is that I think I might be able to pull this off if I can do a Chunk Generator wrapper (more on  TeamTwilight/twilightforest#1277)

**Comment by Drullkus** [comment]
Ideally this should be accomplishable via TeamTwilight/twilightforest@5d64e2f84aa761893286d07e047d0ca659e92c26 now :)

**Comment by Royal-Jelly** [comment]
Thank you kindly Drullkus.

**Comment by alcatrazEscapee** [comment]
So it has come to my attention this means I need to port HexLands to 1.17... well, to the porting we go! :P

**Comment by Royal-Jelly** [comment]
Iou don't need to but its greatly appreciated, and thank you kindly for keeping this mod alive.
