### ISSUE TITLE
Custom Hex Nether Generation

### ISSUE THREAD

**Issue by Darkosto** [alcatrazEscapee/hexlands#4]
Hello! 

I've been working on getting the Nether dimension setup with custom hex generation. I've been unlucky so far and was hoping you could help me out. I've used the same method listed for the Overworld in your readme example and altered the settings to point to the Nether. The Nether still generates with default Hexland settings and seems to not be reading my json file in the dimension folder. Would you be able to show me an example file or confirm custom Nether hexlands is possible?

Here is my file:
```json
{
  "type": "minecraft:the_nether",
  "generator": {
    "type": "hexlands:hexlands",
    "seed": 555,
    "settings": "minecraft:nether",
    "biome_source": {
      "type": "hexlands:hexlands",
      "seed": 555,
      "biome_source": {
        "type": "minecraft:multi_noise",
        "seed": 555,
        "large_biomes": false
      },
      "biome_scale": 16,
      "hex_size": 28,
      "hex_border_threshold": 0.92,
      "border_state": {
        "Name": "minecraft:stone",
        "Properties": {}
      },
      "border_extends_to_bedrock": false,
      "windowed_border": true,
      "no_border": false
    }
  }
}
```

**Comment by alcatrazEscapee** [comment]
It appears that you are missing required properties of the `minecraft:multi_noise` biome source.

As a tip: Vanilla will silently ignore invalid dimension overrides that are placed in the minecraft namespace (I still don't know exactly why this is or how to fix it yet). So, to double check, you can change this to a custom namespace (i.e. `dummy_mod`), and see if there is a log error (which will be more informative than "it doesn't work"). For example, this is the log message I get when including your attached dimension json, but in the `hexlands` namespace:

```
[21:07:19] [Render thread/ERROR] [minecraft/Minecraft]: Error reading worldgen settings after loading data packs: No key weirdness_noise in MapLike[{"type":"minecraft:multi_noise","seed":555}]; No key altitude_noise in MapLike[{"type":"minecraft:multi_noise","seed":555}]; No key humidity_noise in MapLike[{"type":"minecraft:multi_noise","seed":555}]; No key temperature_noise in MapLike[{"type":"minecraft:multi_noise","seed":555}]; No key biomes in MapLike[{"type":"minecraft:multi_noise","seed":555}]
```

You can consult slicedlime's [Examples in 1.16.2](https://github.com/slicedlime/examples/tree/80fb4b8418ff3ff5724f4a0438bb422f58960bd9) for the vanilla `nether.json` and all the required properties there.

**Comment by alcatrazEscapee** [comment]
And as also requested, here is a [working example](https://gist.github.com/alcatrazEscapee/d09ef2efc253a1e0b905a24725899470) for 1.16 nether dimension, as hexlands. (I tested this with a custom `hexlands:nether` dimension and it appeared to work, which I'd recommend over testing replacing the vanilla dimensions for the aforementioned reasons, using `/execute in hexlands:nether run tp Player ~ ~ ~` to travel there.

**Comment by Darkosto** [comment]
This example worked perfectly. Thank you very much for the help on how to debug and get it running!
