### ISSUE TITLE
Update to 1.19.3?

### ISSUE THREAD

**Issue by Patbox** [alcatrazEscapee/hexlands#6]
Hello! Looking as it's been a while and there lacking any 1.19.x update, is this mod still maintained? Was interested in using it, hovewer I prefer using latest versions. If you don't plan on updating it yourself, I would be interested in doing that myself (and I guess pr'ing it?)

**Comment by alcatrazEscapee** [comment]
Please do PR it, the only reason I haven't updated is due to lack of time, and because it required a rewrite for the third time in just as many minecraft versions. See my half-finished branch: https://github.com/alcatrazEscapee/hexlands/commit/25a694e541aaf7e9dd369c689305783e19342a1b
